# Generated by Django 2.2.6 on 2020-02-13 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_genre',
            field=models.TextField(default='programming'),
        ),
    ]
