# Generated by Django 2.2 on 2020-02-13 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='post_views',
        ),
    ]
