# Generated by Django 2.2 on 2020-02-13 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_genre'),
        ('posts', '0005_post_tag'),
    ]

    operations = [
    ]
