# Generated by Django 2.2 on 2020-02-13 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_merge_20200213_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_genre',
        ),
    ]
