# Generated by Django 2.2 on 2020-02-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_post_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_views',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tag',
        ),
    ]
