# Generated by Django 2.2 on 2020-02-21 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='AbsBaseUser',
        ),
    ]
