# Generated by Django 2.2 on 2020-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200221_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absbaseuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
